// Generated by https://quicktype.io

export interface Item {
  url: string;
  id: number;
  owner: string;
  owner_name: string;
  name: string;
  created_date: string;
  active: boolean;
  notes: string;
  best_before: string;
  promise_before: string;
}
